'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dashboard
    
    '''<summary>
    '''fnameProfTbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fnameProfTbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mnameProfTbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnameProfTbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnameProfTbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnameProfTbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''passProfTbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents passProfTbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''confirmpassProfTbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirmpassProfTbox As Global.System.Web.UI.WebControls.TextBox
End Class
