'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class feedback
    
    '''<summary>
    '''Q1TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q1TextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Q2TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q2TextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Q3DPLIST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q3DPLIST As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Q4TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q4TextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Q5TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q5TextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Q6TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q6TextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Q7CALENDER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q7CALENDER As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''Q8TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q8TextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSURVEY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSURVEY As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''surveystatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents surveystatus As Global.System.Web.UI.WebControls.Label
End Class
